apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-api-deployment
  labels:
    app: fortune-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune-api
  template:
    metadata:
      labels:
        app: fortune-api
    spec:
      containers:
      - name: fortune-api
        image: pratiksuman008/fortune-api
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: fortune-api-service
spec:
  selector:
    app.kubernetes.io/name: fortune-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-creator
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups:
  - ""
  resources:
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  - secrets
  - services/proxy
  verbs:
  - get
  - list
  - watch
  - create
  - delete



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-pod-creator
subjects:
- kind: User
  name: checkcluster
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io
